### ISSUE TITLE
util.c:182 (get_devices_from_authfile): Invalid hex number in key

### ISSUE THREAD

**Issue by SuperKaninchen** [Yubico/pam-u2f#179]
After taking quite some time to set up, it didn't work. Whenever I tried to authenticate myself, it would immediately ask for my password. After enabling the debug option, I stumbled upon an error I have found no documentation of:
```
debug(pam_u2f): util.c:182 (get_devices_from_authfile): Invalid hex number in key
debug(pam_u2f): pam-u2f.c:310 (pam_sm_authenticate): Unable to get devices from file /etc/u2f_mappings
debug(pam_u2f): pam-u2f.c:410 (pam_sm_authenticate): done. [Authentication service cannot retrieve authentication info]
```
What is this error caused by and how can I fix it?

**Comment by LDVG** [comment]
Hi,

This looks like an error message from an older version (1.0.8 or so). We just released version 1.1.1, could you try updating and see if you get another error message?

**Comment by SuperKaninchen** [comment]
> 
> 
> Hi,
> 
> This looks like an error message from an older version (1.0.8 or so). We just released version 1.1.1, could you try updating and see if it's resolved or if you get another error message?

I think I actually built from the source I pulled a few days ago, but I'll reinstall as soon as I get home

**Comment by SuperKaninchen** [comment]
> Hi,
> 
> This looks like an error message from an older version (1.0.8 or so). We just released version 1.1.1, could you try updating and see if it's resolved or if you get another error message?

Okay, I just downloaded the 1.1.1 tarball, extracted it, and followed the instructions as documented in the README, but I am still getting the same error

**Comment by LDVG** [comment]
> Okay, I just downloaded the 1.1.1 tarball, extracted it, and followed the instructions as documented in the README, but I am still getting the same error

Hm, that is odd. The source code does not contain the quoted debug message in the OP (`"Invalid hex number in key"`); version 1.0.8 does though. Do you have a conflicting package installed via a package manager or similar?

**Comment by SuperKaninchen** [comment]
> > Okay, I just downloaded the 1.1.1 tarball, extracted it, and followed the instructions as documented in the README, but I am still getting the same error
> 
> Hm, that is odd. The source code for 1.1.1 does not contain the quoted debug message in the OP (`"Invalid hex number in key"`); version 1.0.8 does though. Do you have a conflicting package installed via a package manager or similar?

Turns out I did have 1.0.8 installed through my package manager. But after removing it and reinstalling the build, it doesn't even print any debug information even though the pam settings state otherwise.

**Comment by LDVG** [comment]
> But after removing it and reinstalling the build, it doesn't even print any debug information even though the pam settings state otherwise.

It sounds like PAM is not picking up the module. Where was it installed to on your system?

**Comment by SuperKaninchen** [comment]
> 
> It sounds like PAM is not picking up the module. Where was it installed to on your system?

Libraries have been installed in:
   /lib/x86_64-linux-gnu/security
according to the install script

**Comment by LDVG** [comment]
> /lib/x86_64-linux-gnu/security

Is `pam_u2f.so` present in this directory? What distribution are you running?

**Comment by SuperKaninchen** [comment]
> 
> Is `pam_u2f.so` present in this directory? What distribution are you running?

`-rw-r--r--. 1 root root 155K May 20 15:50 /lib/x86_64-linux-gnu/security/pam_u2f.so`
indicating that the file exists, and I'm running Fedora 32 
`Linux ***** 5.9.15-100.fc32.x86_64 #1 SMP Wed Dec 16 16:49:20 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by LDVG** [comment]
IIRC, the location for PAM modules is slightly different on Fedora (`/usr/lib64/security` or something similar); you may have to adjust `--with-pam-dir=DIR` accordingly when you call `./configure`.

**Comment by SuperKaninchen** [comment]
> IIRC, the location for PAM modules is slightly different on Fedora (`/lib64/security`, `/usr/lib64/security` or something similar); you may have to adjust `--with-pam-dir=DIR` accordingly when you call `./configure`.

Works perfectly fine now. Thank you for your help! :blush:
